// Code generated by "stringer -type CleanupType enum.go"; DO NOT EDIT.

package global

import "strconv"

const _CleanupType_name = "UnconfirmedDeleted"

var _CleanupType_index = [...]uint8{0, 11, 18}

func (i CleanupType) String() string {
	if i < 0 || i >= CleanupType(len(_CleanupType_index)-1) {
		return "CleanupType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CleanupType_name[_CleanupType_index[i]:_CleanupType_index[i+1]]
}
