# .goreleaser.yml
# Build customization
dist: goreleaser-build
builds:
  - main: main.go
    binary: mouthful
    goos:
      # - darwin
      - linux
      # - windows
    goarch:
      - amd64
    hooks:
      pre: ./goreleaser-pre.sh
  - main: main.go
    env:
      - CGO_ENABLED=1
      - CXX_FOR_TARGET=x86_64-w64-mingw32-g++
      - CC_FOR_TARGET=x86_64-w64-mingw32-gcc 
      - CC=x86_64-w64-mingw32-gcc
    binary: mouthful
    goos:
      - windows
    goarch:
      - amd64
    hooks:
      pre: ./goreleaser-pre.sh
# Archive customization
archive:
  format: tar.gz
  files:
    - static/*
    - config.json